# Skip URLs matching these patterns
exclude = [ ]

# Timeout in seconds
timeout = 15

# Retry failed links (helpful for flaky sites)
retry_count = 2

# Accept non-200 status codes (429: rate limits)
accept = [200, 429]
