# ------------------------------------------------------------------------------
# Kubernetes In Docker (KIND) Environment
#
# This will deploy the base development stack on a KIND cluster:
#
#  * Istio Control Plane
#  * Inference Gateway
#
# This will expose the VLLM simulator via InferencePool and an HTTPRoute.
#
# The vLLM simulator is deployment by a kustomization directory that includes this directory
# ------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- destination-rules.yaml
- services.yaml
- ../../../components/istio-control-plane/
- ../../../components/inference-gateway/

patches:
- path: patch-deployments.yaml
- path: patch-gateways.yaml
