# Sample EPP configuration for running without P/D
#
apiVersion: inference.networking.x-k8s.io/v1alpha1
kind: EndpointPickerConfig
plugins:
- name: prefixScorer
  type: prefix-cache
  parameters:
    hashBlockSize: 5
    maxPrefixBlocksToMatch: 256
    lruCapacityPerServer: 31250
- name: decodeFilter
  type: decode-filter
- type: max-score
- type: single-profile
schedulingProfiles:
- name: default
  plugins:
  - pluginRef: decodeFilter
  - pluginRef: max-score
  - pluginRef: prefixScorer
    weight: 50