apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${MODEL_NAME_SAFE}-vllm-sim
  labels:
    app: ${POOL_NAME}
spec:
  replicas: ${VLLM_REPLICA_COUNT}
  selector:
    matchLabels:
      app: ${POOL_NAME}
  template:
    metadata:
      labels:
        app: ${POOL_NAME}
    spec:
      initContainers:
      - name: routing-sidecar
        image: ghcr.io/llm-d/llm-d-routing-sidecar:latest
        imagePullPolicy: IfNotPresent
        args:
        - "--port=8000"
        - "--vllm-port=8200"
        - "--connector=lmcache"
        - "--secure-proxy=false"
        - "--data-parallel-size=${VLLM_DATA_PARALLEL_SIZE}"
        ports:
        - name: sidecar-http
          containerPort: 8000
          protocol: TCP
        - name: sidecar-rank1
          containerPort: 8001
          protocol: TCP
        - name: sidecar-rank2
          containerPort: 8002
          protocol: TCP
        - name: sidecar-rank3
          containerPort: 8003
          protocol: TCP
        - name: sidecar-rank4
          containerPort: 8004
          protocol: TCP
        - name: sidecar-rank5
          containerPort: 8005
          protocol: TCP
        - name: sidecar-rank6
          containerPort: 8006
          protocol: TCP
        - name: sidecar-rank7
          containerPort: 8007
          protocol: TCP
        restartPolicy: Always
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      containers:
      - name: vllm
        image: ghcr.io/llm-d/llm-d-inference-sim:latest
        imagePullPolicy: IfNotPresent
        args:
        - "--port=8200"
        - "--model=${MODEL_NAME}"
        - "--enable-kvcache=${KV_CACHE_ENABLED}"
        - "--kv-cache-size=1024"
        - "--block-size=16"
        - "--zmq-endpoint=tcp://${EPP_NAME}.default.svc.cluster.local:5557"
        - "--event-batch-size=16"
        - "--tokenizers-cache-dir=/tokenizer-cache"
        - "--data-parallel-size=${VLLM_DATA_PARALLEL_SIZE}"
        ports:
        - name: http
          containerPort: 8200
          protocol: TCP
        - name: rank1
          containerPort: 8201
          protocol: TCP
        - name: rank2
          containerPort: 8202
          protocol: TCP
        - name: rank3
          containerPort: 8203
          protocol: TCP
        - name: rank4
          containerPort: 8204
          protocol: TCP
        - name: rank5
          containerPort: 8205
          protocol: TCP
        - name: rank6
          containerPort: 8206
          protocol: TCP
        - name: rank7
          containerPort: 8207
          protocol: TCP
        env:
        - name: PORT
          value: "8200"
        - name: PYTHONHASHSEED
          value: "42"
        volumeMounts:
        - name: tokenizer-cache
          mountPath: /tokenizer-cache
      volumes:
      - name: tokenizer-cache
        emptyDir: {}

