apiVersion: inference.networking.x-k8s.io/v1alpha1
kind: EndpointPickerConfig

plugins:
  - name: file-discovery
    type: file-discovery
    parameters:
      path: /etc/epp/endpoints.yaml
      watchFile: true

  - name: random-picker
    type: random-picker

  - name: metrics-source
    type: metrics-data-source

  - name: metrics-extractor
    type: core-metrics-extractor

discovery:
  pluginRef: file-discovery

schedulingProfiles:
  - name: default
    plugins:
      - pluginRef: random-picker

dataLayer:
  sources:
    - pluginRef: metrics-source
      extractors:
        - pluginRef: metrics-extractor
