// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/go-logr/logr"
	"github.com/llm-d/llm-d-inference-scheduler/pkg/sidecar/proxy/runners/types"
	"net/http"
	"sync"
)

// Ensure, that ProtocolRunnerMock does implement types.ProtocolRunner.
// If this is not the case, regenerate this file with moq.
var _ types.ProtocolRunner = &ProtocolRunnerMock{}

// ProtocolRunnerMock is a mock implementation of types.ProtocolRunner.
//
//	func TestSomethingThatUsesProtocolRunner(t *testing.T) {
//
//		// make and configure a mocked types.ProtocolRunner
//		mockedProtocolRunner := &ProtocolRunnerMock{
//			RunFunc: func(w http.ResponseWriter, r *http.Request, prefillPodHost string, logger logr.Logger)  {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedProtocolRunner in code that requires types.ProtocolRunner
//		// and then make assertions.
//
//	}
type ProtocolRunnerMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(w http.ResponseWriter, r *http.Request, prefillPodHost string, logger logr.Logger)

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// W is the w argument value.
			W http.ResponseWriter
			// R is the r argument value.
			R *http.Request
			// PrefillPodHost is the prefillPodHost argument value.
			PrefillPodHost string
			// Logger is the logger argument value.
			Logger logr.Logger
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *ProtocolRunnerMock) Run(w http.ResponseWriter, r *http.Request, prefillPodHost string, logger logr.Logger) {
	callInfo := struct {
		W              http.ResponseWriter
		R              *http.Request
		PrefillPodHost string
		Logger         logr.Logger
	}{
		W:              w,
		R:              r,
		PrefillPodHost: prefillPodHost,
		Logger:         logger,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	if mock.RunFunc == nil {
		return
	}
	mock.RunFunc(w, r, prefillPodHost, logger)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedProtocolRunner.RunCalls())
func (mock *ProtocolRunnerMock) RunCalls() []struct {
	W              http.ResponseWriter
	R              *http.Request
	PrefillPodHost string
	Logger         logr.Logger
} {
	var calls []struct {
		W              http.ResponseWriter
		R              *http.Request
		PrefillPodHost string
		Logger         logr.Logger
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
