# ------------------------------------------------------------------------------
# DP (Data Parallel) Development Environment
#
# Deploys decode with data-parallel configuration.
# ------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../components/vllm-decode/

patches:
- path: patch-decode.yaml
