apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-p
spec:
  template:
    spec:
      containers:
      - name: vllm
        args:
        - "--model=${MODEL_NAME}"
        - "--port=8000"
        - "--data-parallel-size=${VLLM_DATA_PARALLEL_SIZE}"
        - "--ec-transfer-config"
        - '{"ec_connector": "ECExampleConnector", "ec_role": "ec_consumer", "ec_connector_extra_config": {"shared_storage_path": "/shared-ec-cache"}}'
        volumeMounts:
        - name: uds-socket
          mountPath: /tmp/tokenizer
        - name: ec-cache
          mountPath: /shared-ec-cache
      volumes:
      - name: uds-socket
        emptyDir: {}
      - name: ec-cache
        emptyDir: {}
