name: CI - Push

on:
  push:
    branches:
      - dev
      - main
  pull_request:  # temporary trigger for testing in PRs
    branches:
      - dev
      - main

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Load version information
        id: version
        run: |
          repo="${GITHUB_REPOSITORY##*/}"
          VERSION_FILE=".version.json"
          dev_version=$(jq -r '.["dev-version"]' "$VERSION_FILE")
          prod_version=$(jq -r '.["prod-version"]' "$VERSION_FILE")
          
          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "tag=$dev_version" >> "$GITHUB_OUTPUT"
            echo "project_name=$repo-dev" >> "$GITHUB_OUTPUT"
          elif [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "tag=$prod_version" >> "$GITHUB_OUTPUT"
            echo "project_name=$repo" >> "$GITHUB_OUTPUT"
          else
            echo "tag=$dev_version" >> "$GITHUB_OUTPUT"
            echo "project_name=$repo-dev" >> "$GITHUB_OUTPUT"
          fi
        shell: bash

      - name: Print project name and tag
        run: |
          echo "Project is ${{ steps.version.outputs.project_name }}"
          echo "Tag is ${{ steps.version.outputs.tag }}"

      - name: Build and push image
        uses: ./.github/actions/docker-build-and-push
        with:
          tag: ${{ steps.version.outputs.tag }}
          image-name: ${{ steps.version.outputs.project_name }}
          registry: ghcr.io/llm-d
          github-token: ${{ secrets.GHCR_TOKEN }}
          kv-cache-manager-token: ${{ secrets.KV_CACHE_MANAGER_TOKEN }}